# Generated by Django 3.2 on 2021-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_restaurantinfo_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='second_image',
            field=models.ImageField(default='static/images/pic01.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='third_image',
            field=models.ImageField(default='static/images/pic01.jpg', upload_to='media'),
        ),
    ]
