# Generated by Django 3.2 on 2021-04-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_restaurantreview_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreview',
            name='unique_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
