# Generated by Django 3.2 on 2021-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_restaurantreview_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='price_group',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
