# Generated by Django 3.2 on 2021-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20210418_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
