# Generated by Django 3.2 on 2021-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_restaurantinfo_smoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='pricerange',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
